from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c8719a7c9b0'
down_revision = 'eb28877337cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credit_card',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cardtype', sa.String(length=30), nullable=False),
    sa.Column('number', sa.String(length=30), nullable=False),
    sa.Column('PersonId', sa.Integer(), nullable=False),
    sa.Column('Datum', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['PersonId'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('credit_card')
    # ### end Alembic commands ###
